baseURL = "http://foia.lol/"
languageCode = "en-us"
paginate = 6
theme = "ink-free"
title = "Freedom Of Information"

[permalinks]
posts = "/:year/:month/:title"

[params]
github = "https://github.com/connyay/foia"
maxTags = 7
mode = "auto"
subtitle = "SEC FOIA requests submitted by a retail investor"
toc = true
wpm = 250

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
icon = "rss"
name = "RSS"
url = "/index.xml"

[taxonomies]
tag = "tags"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "github"
tabWidth = 4

[markup.tableOfContents]
endLevel = 3
ordered = true
startLevel = 2
